name: Release
on:
    workflow_run:
        workflows: ['CI'] # <- must match the exact name in ci.yml
        types: [completed]
        branches: [master]

permissions:
    contents: write
    issues: write
    pull-requests: write

jobs:
    release:
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        runs-on: ubuntu-latest
        env:
            HUSKY: 0
        steps:
            - uses: actions/checkout@v4
              with: { fetch-depth: 0 }
            - uses: actions/setup-node@v4
              with:
                  node-version: '20.x'
                  cache: 'npm'
            - run: npm ci --omit=dev
            - name: Semantic Release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: npm run release
