name: Release
on:
    workflow_run:
        workflows: ['CI']
        types: [completed]

permissions:
    contents: write
    issues: write
    pull-requests: write

jobs:
    release:
        # only run after successful CI AND only for master branch
        if: >
            ${{
              github.event.workflow_run.conclusion == 'success' &&
              github.event.workflow_run.head_branch == 'master'
            }}
        runs-on: ubuntu-latest
        env:
            HUSKY: 0
        steps:
            - name: Debug context (optional)
              run: |
                  echo "event: ${{ github.event.workflow_run.event }}"
                  echo "head_branch: ${{ github.event.workflow_run.head_branch }}"
                  echo "conclusion: ${{ github.event.workflow_run.conclusion }}"

            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - uses: actions/setup-node@v4
              with:
                  node-version: '20.x'
                  cache: 'npm'

            - run: npm ci --omit=dev

            - name: Semantic Release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: npm run release
